version: '2.1'
services:
  studio-server:
    image: "datastax/dse-server:latest"
    container_name: my-server
    environment:
      - DS_LICENSE=accept
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
      - 9200:9200
      - 9300:9300
      
  studio-client:
    image: "datastax/dse-studio"
    container_name: my-client
    environment:
      - DS_LICENSE=accept
    links:
      - studio-server
    ports:
      - 9091:9091